/*
 * SPDX-FileCopyrightText: 2025 SAP Spartacus team <spartacus-team@sap.com>
 *
 * SPDX-License-Identifier: Apache-2.0
 * 
 * NOTE: This is an example model generated by Spartacus MCP Server
 */

export type HeroBannerTheme = 'default' | 'dark' | 'light' | 'midnight' | 'brand';

export type HeroBannerSize = 'small' | 'medium' | 'large' | 'full';

export type HeroBannerTextAlign = 'left' | 'center' | 'right';

export interface HeroBannerConfig {
  title?: string;
  subtitle?: string;
  description?: string;
  backgroundImage?: string;
  ctaText?: string;
  ctaLink?: string;
  secondaryCtaText?: string;
  secondaryCtaLink?: string;
  responsive?: boolean;
  animated?: boolean;
  theme?: HeroBannerTheme;
  size?: HeroBannerSize;
  textAlign?: HeroBannerTextAlign;
  mobileContent?: string;
  overlay?: boolean;
  overlayOpacity?: number;
  autoplay?: boolean;
  duration?: number;
}

export interface HeroBannerCtaEvent {
  text: string;
  link: string;
  position: 'primary' | 'secondary';
  title?: string;
}

export interface HeroBannerBreakpoint {
  name: string;
  minWidth: number;
  maxWidth?: number;
}

export interface HeroBannerResponsiveConfig {
  breakpoints: HeroBannerBreakpoint[];
  mobileFirst: boolean;
}

export interface HeroBannerData {
  config: HeroBannerConfig;
  isLoading: boolean;
  isMobile: boolean;
  isTablet: boolean;
  isDesktop: boolean;
}

export interface HeroBannerAnalytics {
  impressions: number;
  clicks: number;
  conversionRate: number;
  lastUpdated: Date;
} 