/*
 * SPDX-FileCopyrightText: 2025 SAP Spartacus team <spartacus-team@sap.com>
 *
 * SPDX-License-Identifier: Apache-2.0
 * 
 * NOTE: This is an example model generated by Spartacus MCP Server
 */

export interface Product {
  id: string;
  name: string;
  description?: string;
  price: number;
  originalPrice?: number;
  currency?: string;
  imageUrl?: string;
  images?: ProductImage[];
  stock: number;
  rating?: number;
  reviewCount?: number;
  category?: string;
  brand?: string;
  sku?: string;
  availability?: ProductAvailability;
  attributes?: ProductAttribute[];
  variants?: ProductVariant[];
  tags?: string[];
  createdAt?: Date;
  updatedAt?: Date;
}

export interface ProductImage {
  url: string;
  alt?: string;
  type: 'thumbnail' | 'main' | 'gallery' | 'zoom';
  order?: number;
}

export interface ProductAttribute {
  name: string;
  value: string;
  type?: 'text' | 'number' | 'boolean' | 'color' | 'size';
  displayName?: string;
}

export interface ProductVariant {
  id: string;
  name: string;
  price?: number;
  stock?: number;
  attributes: ProductAttribute[];
  imageUrl?: string;
}

export type ProductAvailability = 'in_stock' | 'out_of_stock' | 'limited' | 'pre_order';

export type ProductSortOption = 'name' | 'price_asc' | 'price_desc' | 'rating' | 'newest' | 'popularity';

export interface ProductGridConfig {
  columns?: number;
  showPrices?: boolean;
  showRatings?: boolean;
  showAddToCart?: boolean;
  title?: string;
  maxItems?: number;
  responsive?: boolean;
  accessibility?: boolean;
  sortOptions?: ProductSortOption[];
  defaultSort?: ProductSortOption;
  enableFiltering?: boolean;
  enablePagination?: boolean;
  itemsPerPage?: number;
  showProductImages?: boolean;
  showProductDescription?: boolean;
  showStockStatus?: boolean;
  enableQuickView?: boolean;
  enableWishlist?: boolean;
  theme?: 'default' | 'compact' | 'detailed' | 'minimal';
  layout?: 'grid' | 'list' | 'masonry';
}

export interface ProductFilter {
  category?: string[];
  brand?: string[];
  priceRange?: {
    min: number;
    max: number;
  };
  rating?: number;
  availability?: ProductAvailability[];
  attributes?: { [key: string]: string[] };
}

export interface ProductGridState {
  products: Product[];
  filteredProducts: Product[];
  currentPage: number;
  totalPages: number;
  isLoading: boolean;
  error?: string;
  filters: ProductFilter;
  sortBy: ProductSortOption;
}

export interface ProductGridEvent {
  type: 'product_click' | 'add_to_cart' | 'add_to_wishlist' | 'quick_view' | 'filter_change' | 'sort_change' | 'page_change';
  product?: Product;
  data?: any;
  timestamp: Date;
} 